#ifndef STATISTICS_VIEW_EXPORT_H
#define STATISTICS_VIEW_EXPORT_H

#include <QtCore/QtGlobal>

#if defined(STATISTIC_VIEW_LIBRARY)
#  define STATISTIC_VIEW_EXPORT Q_DECL_EXPORT
#else
#  define STATISTIC_VIEW_EXPORT Q_DECL_IMPORT
#endif

#endif // STATISTICS_VIEW_EXPORT_H
