#ifndef EXPRESSION_CALCULATOR_EXPORT_H
#define EXPRESSION_CALCULATOR_EXPORT_H

#include <QtCore/QtGlobal>

#if defined(EXPRESSIONCALCULATOR_LIBRARY)
#  define EXPRESSIONCALCULATOR_EXPORT Q_DECL_EXPORT
#else
#  define EXPRESSIONCALCULATOR_EXPORT Q_DECL_IMPORT
#endif

#endif // EXPRESSION_CALCULATOR_EXPORT_H
